In [1]:
import math
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd
import requests
import numpy as np
import lxml
import re
from random import seed
from collections import Counter
import numpy as np
from sklearn.linear_model import LinearRegression
from datetime import datetime
import pandas as pd
import matplotlib.pyplot as plt
import array
from sklearn.model_selection import train_test_split
#from keras.models import Sequential
#from keras.layers import Dense
import re

C:\Users\MoJo\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.25.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

# Get Link into DataFrame

In [4]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

In [5]:
# URL of the webpage
url = "http://www.alltime-athletics.com/w_100ok.htm"

# Send an HTTP GET request to the URL
response = requests.get(url)

# Parse the HTML content using Beautiful Soup
soup = BeautifulSoup(response.content, "html.parser")

# Use select to find all <pre> elements
pre_elements = soup.select("pre")

In [6]:
# Select the second <pre> element
if len(pre_elements) > 1:
    first_pre_element = pre_elements[0]

    # Get the text content of the second <pre> element
    first_pre_text = first_pre_element.get_text()

    # Split the text into rows
    rows = first_pre_text.strip().split('\n')

    # Split rows into columns
    data = [row.split() for row in rows]

    # Create a Pandas DataFrame
    df = pd.DataFrame(data)
    
    print(df)
else:
    print("No second <pre> element found.")

        0      1     2           3                4    5         6    7   \
0        1  10.49  ±0.0    Florence  Griffith-Joyner  USA  21.12.59  1q1
1        2  10.54  +0.9      Elaine   Thompson-Herah  JAM  28.06.92    1
2        3  10.60  +1.7  Shelly-Ann     Fraser-Pryce  JAM  27.12.86  1rA
3        4  10.61  +1.2    Florence  Griffith-Joyner  USA  21.12.59    1
4        4  10.61  -0.6      Elaine   Thompson-Herah  JAM  28.06.92    1
...    ...    ...   ...         ...              ...  ...       ...  ...
2940  2701  11.09  +0.1         Ewa          Swoboda  POL  26.07.97  1rA
2941  2701  11.09  -0.4   Shashalee           Forbes  JAM  10.05.96  2h3
2942  2701  11.09  +0.7         Mia   Brahe-Pedersen  USA  28.11.05  5s1
2943  2701  11.09  +0.2        Gina     Lückenkemper  GER  21.11.96    7
2944  2701  11.09  +1.2     Melissa        Jefferson  USA  21.02.01    7

                8           9     10    11    12
0     Indianapolis  16.07.1988  None  None  None
1           Eugene  21.08.2021  None  None  None
2         Lausanne  26.08.2021  None  None  None
3     Indianapolis  17.07.1988  None  None  None
4            Tokyo  31.07.2021  None  None  None
...            ...         ...   ...   ...   ...
2940       Chorzów  23.06.2023  None  None  None
2941      Kingston  06.07.2023  None  None  None
2942        Eugene  07.07.2023  None  None  None
2943       Chorzów  16.07.2023  None  None  None
2944        London  23.07.2023  None  None  None

[2945 rows x 13 columns]

In [7]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,1,10.49,±0.0,Florence,Griffith-Joyner,USA,21.12.59,1q1,Indianapolis,16.07.1988,None,None,None
1,2,10.54,+0.9,Elaine,Thompson-Herah,JAM,28.06.92,1,Eugene,21.08.2021,None,None,None
2,3,10.60,+1.7,Shelly-Ann,Fraser-Pryce,JAM,27.12.86,1rA,Lausanne,26.08.2021,None,None,None
3,4,10.61,+1.2,Florence,Griffith-Joyner,USA,21.12.59,1,Indianapolis,17.07.1988,None,None,None
4,4,10.61,-0.6,Elaine,Thompson-Herah,JAM,28.06.92,1,Tokyo,31.07.2021,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2940,2701,11.09,+0.1,Ewa,Swoboda,POL,26.07.97,1rA,Chorzów,23.06.2023,None,None,None
2941,2701,11.09,-0.4,Shashalee,Forbes,JAM,10.05.96,2h3,Kingston,06.07.2023,None,None,None
2942,2701,11.09,+0.7,Mia,Brahe-Pedersen,USA,28.11.05,5s1,Eugene,07.07.2023,None,None,None
2943,2701,11.09,+0.2,Gina,Lückenkemper,GER,21.11.96,7,Chorzów,16.07.2023,None,None,None
2944,2701,11.09,+1.2,Melissa,Jefferson,USA,21.02.01,7,London,23.07.2023,None,None,None

In [8]:
df["Athlete"] = df[3].astype(str)+df[4].astype(str)

In [9]:
WindReadings = []
for i in range(0,len(df)):
    WindReadings.append(df[2][i][2:])
WindReadings

['.0',
 '.9',
 '.7',
 '.2',
 '.6',
 '.0',
 '.4',
 '.3',
 '.2',
 '.7',
 '.1',
 '.6',
 '.8',
 '.0',
 '.5',
 '.1',
 '.4',
 '.5',
 '.8',
 '.3',
 '.6',
 '.1',
 '.0',
 '.6',
 '.3',
 '.1',
 '.1',
 '.0',
 '.3',
 '.5',
 '.8',
 '.1',
 '.0',
 '.6',
 '.4',
 '.1',
 '.0',
 '.0',
 '.0',
 '.3',
 '.6',
 '.6',
 '.3',
 '.4',
 '.0',
 '.1',
 '.6',
 '.6',
 '.3',
 '.9',
 '.8',
 '.6',
 '.3',
 '.2',
 '.0',
 '.2',
 '.1',
 '.6',
 '.6',
 '.6',
 '.4',
 '.1',
 '.5',
 '.6',
 '.9',
 '.7',
 '.2',
 '.7',
 '.9',
 '.3',
 '.1',
 '.3',
 '.0',
 '.6',
 '.9',
 '.9',
 '.2',
 '.9',
 '.9',
 '.7',
 '.7',
 '.2',
 '.9',
 '.9',
 '.0',
 '.7',
 '.4',
 '.1',
 '.8',
 '.0',
 '.8',
 '.4',
 '.5',
 '.6',
 '.0',
 '.0',
 '.8',
 '.3',
 '.7',
 '.8',
 '.3',
 '.5',
 '.6',
 '.9',
 '.6',
 '.2',
 '.6',
 '.7',
 '.0',
 '.6',
 '.1',
 '.1',
 '.1',
 '.5',
 '.4',
 '.2',
 '.2',
 '.7',
 '.6',
 '.8',
 '.1',
 '.4',
 '.7',
 '.8',
 '.2',
 '.7',
 '.2',
 '.7',
 '.2',
 '.8',
 '.3',
 '.2',
 '.1',
 '.0',
 '.5',
 '.7',
 '.7',
 '.7',
 '.2',
 '.3',
 '.5',
 '.4',
 '.4',
 '.7',
 '.5',
 '.8',
 '.4',
 '.8',
 '.4',
 '.0',
 '.0',
 '.5',
 '.3',
 '.3',
 '.4',
 '.1',
 '.5',
 '.3',
 '.7',
 '.4',
 '.6',
 '.7',
 '.5',
 '.9',
 '.1',
 '.0',
 '.6',
 '.1',
 '.5',
 '.2',
 '.6',
 '.0',
 '.7',
 '.3',
 '.7',
 '.0',
 '.0',
 '.0',
 '.3',
 '.4',
 '.9',
 '.4',
 '.0',
 '.4',
 '.1',
 '.1',
 '.3',
 '.4',
 '.1',
 '.4',
 '.8',
 '.5',
 '.0',
 '.4',
 '.6',
 '.2',
 '.7',
 '.6',
 '.5',
 '.1',
 '.1',
 '.9',
 '.3',
 '.3',
 '.8',
 '.6',
 '.1',
 '.7',
 '.1',
 '.7',
 '.0',
 '.2',
 '.3',
 '.0',
 '.4',
 '.5',
 '.3',
 '.1',
 '.7',
 '.6',
 '.9',
 '.1',
 '.8',
 '.3',
 '.5',
 '.5',
 '.4',
 '.1',
 '.2',
 '.1',
 '.1',
 '.0',
 '.3',
 '.2',
 '.2',
 '.2',
 '.6',
 '.0',
 '.5',
 '.9',
 '.9',
 '.4',
 '.6',
 '.4',
 '.8',
 '.5',
 '.4',
 '.0',
 '.7',
 '.4',
 '.2',
 '.5',
 '.0',
 '.8',
 '.1',
 '.6',
 '.3',
 '.2',
 '.0',
 '.1',
 '.5',
 '.0',
 '.3',
 '.2',
 '.3',
 '.1',
 '.9',
 '.2',
 '.4',
 '.0',
 '.8',
 '.6',
 '.0',
 '.0',
 '.9',
 '.2',
 '.3',
 '.7',
 '.1',
 '.2',
 '.7',
 '.9',
 '.0',
 '.0',
 '.1',
 '.1',
 '.1',
 '.0',
 '.2',
 '.3',
 '.5',
 '.5',
 '.1',
 '.9',
 '.6',
 '.9',
 '.9',
 '.1',
 '.2',
 '.2',
 '.0',
 '.2',
 '.3',
 '.3',
 '.0',
 '.0',
 '.3',
 '.0',
 '.3',
 '.7',
 '.0',
 '.0',
 '.6',
 '.7',
 '.8',
 '.1',
 '.7',
 '.9',
 '.8',
 '.3',
 '.8',
 '.8',
 '.5',
 '.4',
 '.0',
 '.3',
 '.2',
 '.6',
 '.8',
 '.8',
 '.2',
 '.2',
 '.1',
 '.0',
 '.0',
 '.0',
 '.9',
 '.9',
 '.6',
 '.0',
 '.2',
 '.0',
 '.8',
 '.0',
 '.0',
 '.1',
 '.4',
 '.2',
 '.7',
 '.5',
 '.5',
 '.7',
 '.2',
 '.5',
 '.3',
 '.6',
 '.9',
 '.9',
 '.5',
 '.3',
 '.3',
 '.5',
 '.5',
 '.9',
 '.5',
 '.0',
 '.3',
 '.8',
 '.7',
 '.1',
 '.0',
 '.8',
 '.8',
 '.1',
 '.6',
 '.9',
 '.6',
 '.3',
 '.4',
 '.1',
 '.5',
 '.0',
 '.0',
 '.0',
 '.1',
 '.2',
 '.0',
 '.1',
 '.2',
 '.0',
 '.0',
 '.0',
 '.5',
 '.5',
 '.2',
 '.1',
 '.6',
 '.4',
 '.3',
 '.6',
 '.6',
 '.6',
 '.6',
 '.9',
 '.2',
 '.0',
 '.9',
 '.9',
 '.7',
 '.6',
 '.1',
 '.4',
 '.4',
 '.5',
 '.6',
 '.9',
 '.4',
 '.5',
 '.7',
 '.6',
 '.8',
 '.4',
 '.0',
 '.0',
 '.7',
 '.0',
 '.0',
 '.1',
 '.1',
 '.8',
 '.4',
 '.4',
 '.7',
 '.7',
 '.1',
 '.0',
 '.9',
 '.8',
 '.2',
 '.0',
 '.0',
 '.3',
 '.6',
 '.5',
 '.6',
 '.3',
 '.5',
 '.9',
 '.9',
 '.3',
 '.1',
 '.1',
 '.8',
 '.9',
 '.6',
 '.0',
 '.1',
 '.4',
 '.8',
 '.7',
 '.0',
 '.6',
 '.5',
 '.2',
 '.2',
 '.8',
 '.2',
 '.7',
 '.2',
 '.4',
 '.6',
 '.7',
 '.5',
 '.4',
 '.1',
 '.4',
 '.6',
 '.1',
 '.0',
 '.9',
 '.3',
 '.3',
 '.1',
 '.5',
 '.0',
 '.9',
 '.0',
 '.9',
 '.4',
 '.0',
 '.6',
 '.7',
 '.8',
 '.5',
 '.0',
 '.3',
 '.7',
 '.2',
 '.8',
 '.1',
 '.2',
 '.2',
 '.0',
 '.6',
 '.6',
 '.2',
 '.5',
 '.7',
 '.4',
 '.7',
 '.3',
 '.3',
 '.6',
 '.8',
 '.5',
 '.8',
 '.4',
 '.6',
 '.8',
 '.0',
 '.3',
 '.0',
 '.2',
 '.6',
 '.8',
 '.1',
 '.9',
 '.0',
 '.0',
 '.9',
 '.6',
 '.1',
 '.5',
 '.0',
 '.4',
 '.1',
 '.9',
 '.0',
 '.9',
 '.2',
 '.1',
 '.2',
 '.0',
 '.1',
 '.2',
 '.1',
 '.3',
 '.2',
 '.7',
 '.1',
 '.9',
 '.0',
 '.0',
 '.2',
 '.5',
 '.0',
 '.0',
 '.4',
 '.5',
 '.2',
 '.6',
 '.1',
 '.8',
 '.5',
 '.4',
 '.5',
 '.6',
 '.7',
 '.8',
 '.4',
 '.8',
 '.7',
 '.5',
 '.7',
 '.7',
 '.0',
 '.8',
 '.8',
 '.2',
 '.8',
 '.6',
 '.3',
 '.0',
 '.9',
 '.7',
 '.0',
 '.1',
 '.6',
 '.1',
 '.8',
 '.6',
 '.2',
 '.8',
 '.0',
 '.5',
 '.2',
 '.5',
 '.9',
 '.4',
 '.3',
 '.1',
 '.4',
 '.3',
 '.6',
 '.0',
 '.9',
 '.1',
 '.1',
 '.3',
 '.2',
 '.2',
 '.5',
 '.0',
 '.3',
 '.5',
 '.2',
 '.4',
 '.4',
 '.7',
 '.1',
 '.1',
 '.8',
 '.2',
 '.7',
 '.1',
 '.3',
 '.1',
 '.2',
 '.2',
 '.4',
 '.3',
 '.2',
 '.4',
 '.5',
 '.4',
 '.1',
 '.2',
 '.1',
 '.2',
 '.1',
 '.6',
 '.6',
 '.0',
 '.8',
 '.7',
 '.4',
 '.4',
 '.4',
 '.4',
 '.8',
 '.6',
 '.2',
 '.4',
 '.6',
 '.1',
 '.6',
 '.6',
 '.3',
 '.0',
 '.0',
 '.0',
 '.0',
 '.7',
 '.1',
 '.0',
 '.2',
 '.9',
 '.9',
 '.0',
 '.7',
 '.7',
 '.1',
 '.1',
 '.1',
 '.7',
 '.1',
 '.9',
 '.3',
 '.0',
 '.9',
 '.9',
 '.9',
 '.3',
 '.7',
 '.3',
 '.7',
 '.4',
 '.4',
 '.9',
 '.7',
 '.6',
 '.5',
 '.2',
 '.5',
 '.8',
 '.1',
 '.5',
 '.3',
 '.8',
 '.2',
 '.5',
 '.5',
 '.5',
 '.3',
 '.5',
 '.1',
 '.3',
 '.4',
 '.0',
 '.6',
 '.6',
 '.7',
 '.6',
 '.3',
 '.0',
 '.9',
 '.5',
 '.8',
 '.9',
 '.5',
 '.0',
 '.2',
 '.2',
 '.2',
 '.0',
 '.2',
 '.1',
 '.1',
 '.4',
 '.7',
 '.7',
 '.3',
 '.2',
 '.6',
 '.9',
 '.5',
 '.1',
 '.3',
 '.4',
 '.8',
 '.0',
 '.4',
 '.9',
 '.1',
 '.0',
 '.8',
 '.1',
 '.1',
 '.2',
 '.1',
 '.3',
 '.5',
 '.6',
 '.3',
 '.7',
 '.3',
 '.0',
 '.8',
 '.0',
 '.7',
 '.1',
 '.3',
 '.2',
 '.0',
 '.8',
 '.6',
 '.4',
 '.1',
 '.4',
 '.4',
 '.9',
 '.7',
 '.0',
 '.8',
 '.3',
 '.1',
 '.1',
 '.6',
 '.6',
 '.3',
 '.1',
 '.3',
 '.1',
 '.6',
 '.9',
 '.4',
 '.5',
 '.4',
 '.2',
 '.8',
 '.1',
 '.4',
 '.1',
 '.1',
 '.8',
 '.3',
 '.3',
 '.9',
 '.8',
 '.9',
 '.0',
 '.4',
 '.9',
 '.5',
 '.0',
 '.3',
 '.0',
 '.2',
 '.2',
 '.0',
 '.4',
 '.5',
 '.3',
 '.9',
 '.8',
 '.9',
 '.9',
 '.1',
 '.1',
 '.7',
 '.8',
 '.4',
 '.3',
 '.2',
 '.9',
 '.2',
 '.5',
 '.0',
 '.1',
 '.2',
 '.5',
 '.1',
 '.7',
 '.4',
 '.3',
 '.1',
 '.3',
 '.4',
 '.2',
 '.9',
 '.0',
 '.9',
 '.4',
 '.4',
 '.8',
 '.9',
 '.4',
 '.9',
 '.0',
 '.4',
 '.9',
 '.9',
 '.0',
 '.4',
 '.8',
 '.2',
 '.9',
 '.0',
 '.0',
 '.3',
 '.7',
 '.3',
 '.0',
 '.3',
 '.1',
 '.4',
 '.1',
 '.5',
 '.6',
 '.9',
 '.5',
 '.5',
 '.9',
 '.1',
 '.7',
 '.2',
 '.1',
 '.0',
 '.3',
 '.3',
 '.9',
 '.9',
 '.7',
 '.6',
 '.8',
 '.6',
 '.0',
 '.8',
 '.8',
 '.2',
 '.4',
 '.9',
 '.4',
 '.0',
 '.1',
 '.4',
 '.0',
 '.2',
 '.8',
 '.9',
 '.0',
 '.5',
 '.5',
 '.2',
 '.8',
 '.3',
 '.9',
 '.8',
 '.0',
 '.9',
 '.1',
 '.5',
 '.5',
 '.2',
 '.1',
 '.3',
 '.4',
 '.1',
 '.2',
 '.1',
 '.1',
 '.5',
 '.0',
 '.1',
 '.7',
 '.1',
 '.1',
 '.3',
 '.0',
 '.4',
 '.2',
 '.1',
 '.0',
 '.1',
 '.1',
 '.4',
 '.4',
 '.4',
 '.3',
 '.1',
 '.7',
 '.9',
 '.7',
 '.8',
 '.3',
 '.0',
 '.2',
 '.0',
 '.3',
 '.4',
 '.4',
 '.1',
 '.7',
 '.4',
 '.1',
 '.3',
 '.3',
 '.3',
 '.1',
 '.8',
 '.8',
 '.5',
 '.2',
 '.2',
 '.2',
 '.3',
 '.6',
 '.4',
 '.8',
 '.2',
 '.7',
 '.5',
 '.3',
 '.2',
 '.8',
 '.2',
 '.1',
 '.2',
 '.6',
 '.7',
 '.3',
 '.3',
 '.6',
 '.4',
 '.6',
 '.1',
 '.5',
 '.0',
 '.2',
 '.4',
 '.9',
 '.6',
 '.1',
 '.2',
 '.7',
 '.8',
 '.6',
 '.7',
 '.6',
 '.0',
 ...]

In [10]:
df['WindReading'] = WindReadings

In [11]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,Athlete,WindReading
0,1,10.49,±0.0,Florence,Griffith-Joyner,USA,21.12.59,1q1,Indianapolis,16.07.1988,None,None,None,FlorenceGriffith-Joyner,.0
1,2,10.54,+0.9,Elaine,Thompson-Herah,JAM,28.06.92,1,Eugene,21.08.2021,None,None,None,ElaineThompson-Herah,.9
2,3,10.60,+1.7,Shelly-Ann,Fraser-Pryce,JAM,27.12.86,1rA,Lausanne,26.08.2021,None,None,None,Shelly-AnnFraser-Pryce,.7
3,4,10.61,+1.2,Florence,Griffith-Joyner,USA,21.12.59,1,Indianapolis,17.07.1988,None,None,None,FlorenceGriffith-Joyner,.2
4,4,10.61,-0.6,Elaine,Thompson-Herah,JAM,28.06.92,1,Tokyo,31.07.2021,None,None,None,ElaineThompson-Herah,.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2940,2701,11.09,+0.1,Ewa,Swoboda,POL,26.07.97,1rA,Chorzów,23.06.2023,None,None,None,EwaSwoboda,.1
2941,2701,11.09,-0.4,Shashalee,Forbes,JAM,10.05.96,2h3,Kingston,06.07.2023,None,None,None,ShashaleeForbes,.4
2942,2701,11.09,+0.7,Mia,Brahe-Pedersen,USA,28.11.05,5s1,Eugene,07.07.2023,None,None,None,MiaBrahe-Pedersen,.7
2943,2701,11.09,+0.2,Gina,Lückenkemper,GER,21.11.96,7,Chorzów,16.07.2023,None,None,None,GinaLückenkemper,.2
2944,2701,11.09,+1.2,Melissa,Jefferson,USA,21.02.01,7,London,23.07.2023,None,None,None,MelissaJefferson,.2

In [12]:
WorkingDataSet = df[[0, 1, 'Athlete','WindReading',5,6,8,9]]
WorkingDataSet

,0,1,Athlete,WindReading,5,6,8,9
0,1,10.49,FlorenceGriffith-Joyner,.0,USA,21.12.59,Indianapolis,16.07.1988
1,2,10.54,ElaineThompson-Herah,.9,JAM,28.06.92,Eugene,21.08.2021
2,3,10.60,Shelly-AnnFraser-Pryce,.7,JAM,27.12.86,Lausanne,26.08.2021
3,4,10.61,FlorenceGriffith-Joyner,.2,USA,21.12.59,Indianapolis,17.07.1988
4,4,10.61,ElaineThompson-Herah,.6,JAM,28.06.92,Tokyo,31.07.2021
...,...,...,...,...,...,...,...,...
2940,2701,11.09,EwaSwoboda,.1,POL,26.07.97,Chorzów,23.06.2023
2941,2701,11.09,ShashaleeForbes,.4,JAM,10.05.96,Kingston,06.07.2023
2942,2701,11.09,MiaBrahe-Pedersen,.7,USA,28.11.05,Eugene,07.07.2023
2943,2701,11.09,GinaLückenkemper,.2,GER,21.11.96,Chorzów,16.07.2023
2944,2701,11.09,MelissaJefferson,.2,USA,21.02.01,London,23.07.2023

In [13]:
new_column_names = ['RANKINGS','TIMES','ATHLETE','WINDREADING','COUNTRY','BIRTHYEAR','LOCATION','DATEOFRUN']
WorkingDataSet.columns = new_column_names
WorkingDataSet

,RANKINGS,TIMES,ATHLETE,WINDREADING,COUNTRY,BIRTHYEAR,LOCATION,DATEOFRUN
0,1,10.49,FlorenceGriffith-Joyner,.0,USA,21.12.59,Indianapolis,16.07.1988
1,2,10.54,ElaineThompson-Herah,.9,JAM,28.06.92,Eugene,21.08.2021
2,3,10.60,Shelly-AnnFraser-Pryce,.7,JAM,27.12.86,Lausanne,26.08.2021
3,4,10.61,FlorenceGriffith-Joyner,.2,USA,21.12.59,Indianapolis,17.07.1988
4,4,10.61,ElaineThompson-Herah,.6,JAM,28.06.92,Tokyo,31.07.2021
...,...,...,...,...,...,...,...,...
2940,2701,11.09,EwaSwoboda,.1,POL,26.07.97,Chorzów,23.06.2023
2941,2701,11.09,ShashaleeForbes,.4,JAM,10.05.96,Kingston,06.07.2023
2942,2701,11.09,MiaBrahe-Pedersen,.7,USA,28.11.05,Eugene,07.07.2023
2943,2701,11.09,GinaLückenkemper,.2,GER,21.11.96,Chorzów,16.07.2023
2944,2701,11.09,MelissaJefferson,.2,USA,21.02.01,London,23.07.2023

In [14]:
WorkingDataSet.to_csv('ProWomens100m.csv', index=False)