In [1]:
import math
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd
import requests
import numpy as np
import lxml
import re
from random import seed
from collections import Counter
import numpy as np
from sklearn.linear_model import LinearRegression
from datetime import datetime
import pandas as pd
import matplotlib.pyplot as plt
import array
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
import re

C:\Users\MoJo\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.25.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

# Get Link into DataFrame

In [48]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

In [49]:
# URL of the webpage
url = "https://www.alltime-athletics.com/m_100ok.htm"

# Send an HTTP GET request to the URL
response = requests.get(url)

# Parse the HTML content using Beautiful Soup
soup = BeautifulSoup(response.content, "html.parser")

# Use select to find all <pre> elements
pre_elements = soup.select("pre")

In [66]:
# Select the second <pre> element
if len(pre_elements) > 1:
    first_pre_element = pre_elements[0]

    # Get the text content of the second <pre> element
    first_pre_text = first_pre_element.get_text()

    # Split the text into rows
    rows = first_pre_text.strip().split('\n')

    # Split rows into columns
    data = [row.split() for row in rows]

    # Create a Pandas DataFrame
    df = pd.DataFrame(data)
    
    print(df)
else:
    print("No second <pre> element found.")

        0      1     2       3        4      5         6         7   \
0        1   9.58  +0.9   Usain     Bolt    JAM  21.08.86         1
1        2   9.63  +1.5   Usain     Bolt    JAM  21.08.86         1
2        3   9.69  ±0.0   Usain     Bolt    JAM  21.08.86         1
3        3   9.69  +2.0   Tyson      Gay    USA  09.08.82         1
4        3   9.69  -0.1   Yohan    Blake    JAM  26.12.89         1
...    ...    ...   ...     ...      ...    ...       ...       ...
4096  3678  10.09  +0.9   Reece  Prescod    GBR  29.02.96       1s1
4097  3678  10.09  +2.0   Tyler   Azcano    USA  08.03.04         2
4098  3678  10.09  -0.1  Ackeem    Blake    JAM  21.01.02         2
4099  3678  10.09  +0.3   Abdul    Hakim   Sani     Brown       JPN
4100  3678  10.09  +0.5  Arthur      Gue  Cissé       CIV  29.12.96

                  8           9           10          11    12    13    14  \
0             Berlin  16.08.2009        None        None  None  None  None
1             London  05.08.2012        None        None  None  None  None
2            Beijing  16.08.2008        None        None  None  None  None
3           Shanghai  20.09.2009        None        None  None  None  None
4           Lausanne  23.08.2012        None        None  None  None  None
...              ...         ...         ...         ...   ...   ...   ...
4096      Manchester  08.07.2023        None        None  None  None  None
4097          Eugene  08.07.2023        None        None  None  None  None
4098  Székesfehérvár  18.07.2023        None        None  None  None  None
4099        06.03.99         1rB      Luzern  20.07.2023  None  None  None
4100             4rA      Luzern  20.07.2023        None  None  None  None

        15
0     None
1     None
2     None
3     None
4     None
...    ...
4096  None
4097  None
4098  None
4099  None
4100  None

[4101 rows x 16 columns]

In [67]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,1,9.58,+0.9,Usain,Bolt,JAM,21.08.86,1,Berlin,16.08.2009,None,None,None,None,None,None
1,2,9.63,+1.5,Usain,Bolt,JAM,21.08.86,1,London,05.08.2012,None,None,None,None,None,None
2,3,9.69,±0.0,Usain,Bolt,JAM,21.08.86,1,Beijing,16.08.2008,None,None,None,None,None,None
3,3,9.69,+2.0,Tyson,Gay,USA,09.08.82,1,Shanghai,20.09.2009,None,None,None,None,None,None
4,3,9.69,-0.1,Yohan,Blake,JAM,26.12.89,1,Lausanne,23.08.2012,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4096,3678,10.09,+0.9,Reece,Prescod,GBR,29.02.96,1s1,Manchester,08.07.2023,None,None,None,None,None,None
4097,3678,10.09,+2.0,Tyler,Azcano,USA,08.03.04,2,Eugene,08.07.2023,None,None,None,None,None,None
4098,3678,10.09,-0.1,Ackeem,Blake,JAM,21.01.02,2,Székesfehérvár,18.07.2023,None,None,None,None,None,None
4099,3678,10.09,+0.3,Abdul,Hakim,Sani,Brown,JPN,06.03.99,1rB,Luzern,20.07.2023,None,None,None,None
4100,3678,10.09,+0.5,Arthur,Gue,Cissé,CIV,29.12.96,4rA,Luzern,20.07.2023,None,None,None,None,None

In [68]:
df["Athlete"] = df[3].astype(str)+df[4].astype(str)

In [69]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,Athlete
0,1,9.58,+0.9,Usain,Bolt,JAM,21.08.86,1,Berlin,16.08.2009,None,None,None,None,None,None,UsainBolt
1,2,9.63,+1.5,Usain,Bolt,JAM,21.08.86,1,London,05.08.2012,None,None,None,None,None,None,UsainBolt
2,3,9.69,±0.0,Usain,Bolt,JAM,21.08.86,1,Beijing,16.08.2008,None,None,None,None,None,None,UsainBolt
3,3,9.69,+2.0,Tyson,Gay,USA,09.08.82,1,Shanghai,20.09.2009,None,None,None,None,None,None,TysonGay
4,3,9.69,-0.1,Yohan,Blake,JAM,26.12.89,1,Lausanne,23.08.2012,None,None,None,None,None,None,YohanBlake
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4096,3678,10.09,+0.9,Reece,Prescod,GBR,29.02.96,1s1,Manchester,08.07.2023,None,None,None,None,None,None,ReecePrescod
4097,3678,10.09,+2.0,Tyler,Azcano,USA,08.03.04,2,Eugene,08.07.2023,None,None,None,None,None,None,TylerAzcano
4098,3678,10.09,-0.1,Ackeem,Blake,JAM,21.01.02,2,Székesfehérvár,18.07.2023,None,None,None,None,None,None,AckeemBlake
4099,3678,10.09,+0.3,Abdul,Hakim,Sani,Brown,JPN,06.03.99,1rB,Luzern,20.07.2023,None,None,None,None,AbdulHakim
4100,3678,10.09,+0.5,Arthur,Gue,Cissé,CIV,29.12.96,4rA,Luzern,20.07.2023,None,None,None,None,None,ArthurGue

In [71]:
WindReadings = []
for i in range(0,len(df)):
    WindReadings.append(df[2][i][2:])
WindReadings

['.9',
 '.5',
 '.0',
 '.0',
 '.1',
 '.9',
 '.7',
 '.2',
 '.7',
 '.9',
 '.1',
 '.5',
 '.9',
 '.4',
 '.8',
 '.3',
 '.1',
 '.4',
 '.6',
 '.2',
 '.4',
 '.6',
 '.5',
 '.0',
 '.6',
 '.3',
 '.9',
 '.4',
 '.3',
 '.6',
 '.9',
 '.5',
 '.2',
 '.8',
 '.0',
 '.4',
 '.9',
 '.0',
 '.3',
 '.1',
 '.2',
 '.1',
 '.1',
 '.6',
 '.5',
 '.5',
 '.3',
 '.1',
 '.2',
 '.3',
 '.8',
 '.6',
 '.1',
 '.5',
 '.6',
 '.8',
 '.1',
 '.0',
 '.3',
 '.2',
 '.1',
 '.5',
 '.2',
 '.0',
 '.4',
 '.4',
 '.6',
 '.5',
 '.0',
 '.1',
 '.8',
 '.7',
 '.7',
 '.1',
 '.3',
 '.3',
 '.5',
 '.3',
 '.5',
 '.7',
 '.7',
 '.9',
 '.9',
 '.5',
 '.3',
 '.7',
 '.2',
 '.8',
 '.0',
 '.5',
 '.3',
 '.9',
 '.3',
 '.0',
 '.5',
 '.8',
 '.3',
 '.9',
 '.6',
 '.2',
 '.1',
 '.9',
 '.5',
 '.2',
 '.8',
 '.6',
 '.6',
 '.7',
 '.1',
 '.5',
 '.5',
 '.7',
 '.1',
 '.1',
 '.0',
 '.1',
 '.3',
 '.0',
 '.1',
 '.6',
 '.6',
 '.7',
 '.2',
 '.3',
 '.9',
 '.5',
 '.8',
 '.4',
 '.0',
 '.0',
 '.8',
 '.8',
 '.2',
 '.4',
 '.2',
 '.8',
 '.4',
 '.1',
 '.4',
 '.2',
 '.6',
 '.2',
 '.5',
 '.2',
 '.1',
 '.0',
 '.0',
 '.4',
 '.8',
 '.1',
 '.3',
 '.4',
 '.1',
 '.3',
 '.9',
 '.8',
 '.0',
 '.2',
 '.9',
 '.9',
 '.8',
 '.6',
 '.8',
 '.6',
 '.8',
 '.2',
 '.7',
 '.5',
 '.1',
 '.3',
 '.9',
 '.3',
 '.2',
 '.6',
 '.3',
 '.6',
 '.2',
 '.7',
 '.4',
 '.4',
 '.0',
 '.8',
 '.0',
 '.6',
 '.0',
 '.0',
 '.0',
 '.2',
 '.8',
 '.1',
 '.1',
 '.4',
 '.5',
 '.2',
 '.1',
 '.0',
 '.8',
 '.4',
 '.0',
 '.1',
 '.4',
 '.4',
 '.0',
 '.2',
 '.2',
 '.0',
 '.9',
 '.0',
 '.0',
 '.4',
 '.1',
 '.5',
 '.5',
 '.5',
 '.4',
 '.0',
 '.9',
 '.1',
 '.8',
 '.3',
 '.5',
 '.9',
 '.0',
 '.8',
 '.1',
 '.1',
 '.5',
 '.7',
 '.8',
 '.5',
 '.9',
 '.0',
 '.6',
 '.0',
 '.9',
 '.6',
 '.6',
 '.4',
 '.0',
 '.1',
 '.2',
 '.0',
 '.4',
 '.0',
 '.3',
 '.3',
 '.9',
 '.1',
 '.9',
 '.2',
 '.4',
 '.7',
 '.6',
 '.2',
 '.8',
 '.1',
 '.4',
 '.6',
 '.3',
 '.8',
 '.9',
 '.7',
 '.2',
 '.0',
 '.0',
 '.3',
 '.5',
 '.2',
 '.3',
 '.3',
 '.1',
 '.5',
 '.0',
 '.4',
 '.2',
 '.0',
 '.6',
 '.0',
 '.8',
 '.6',
 '.3',
 '.7',
 '.7',
 '.4',
 '.3',
 '.6',
 '.7',
 '.5',
 '.7',
 '.8',
 '.9',
 '.1',
 '.2',
 '.1',
 '.6',
 '.4',
 '.3',
 '.9',
 '.0',
 '.8',
 '.8',
 '.1',
 '.8',
 '.9',
 '.9',
 '.3',
 '.5',
 '.0',
 '.5',
 '.2',
 '.2',
 '.4',
 '.3',
 '.1',
 '.0',
 '.3',
 '.6',
 '.9',
 '.5',
 '.3',
 '.0',
 '.2',
 '.7',
 '.0',
 '.3',
 '.1',
 '.6',
 '.2',
 '.4',
 '.1',
 '.7',
 '.1',
 '.1',
 '.4',
 '.0',
 '.8',
 '.9',
 '.5',
 '.6',
 '.2',
 '.0',
 '.4',
 '.2',
 '.8',
 '.8',
 '.3',
 '.7',
 '.0',
 '.8',
 '.3',
 '.6',
 '.4',
 '.8',
 '.0',
 '.4',
 '.8',
 '.6',
 '.1',
 '.1',
 '.2',
 '.3',
 '.8',
 '.1',
 '.8',
 '.2',
 '.2',
 '.7',
 '.3',
 '.2',
 '.1',
 '.0',
 '.0',
 '.9',
 '.6',
 '.1',
 '.2',
 '.3',
 '.3',
 '.0',
 '.4',
 '.5',
 '.1',
 '.0',
 '.1',
 '.7',
 '.4',
 '.4',
 '.7',
 '.2',
 '.8',
 '.3',
 '.5',
 '.5',
 '.9',
 '.9',
 '.2',
 '.2',
 '.8',
 '.7',
 '.7',
 '.3',
 '.4',
 '.8',
 '.2',
 '.3',
 '.5',
 '.7',
 '.0',
 '.2',
 '.4',
 '.2',
 '.4',
 '.6',
 '.6',
 '.4',
 '.6',
 '.4',
 '.0',
 '.1',
 '.9',
 '.3',
 '.6',
 '.3',
 '.4',
 '.1',
 '.6',
 '.5',
 '.4',
 '.5',
 '.4',
 '.3',
 '.8',
 '.8',
 '.8',
 '.0',
 '.5',
 '.0',
 '.2',
 '.1',
 '.0',
 '.1',
 '.3',
 '.0',
 '.1',
 '.2',
 '.9',
 '.9',
 '.6',
 '.0',
 '.4',
 '.3',
 '.3',
 '.7',
 '.8',
 '.7',
 '.4',
 '.1',
 '.8',
 '.1',
 '.6',
 '.4',
 '.8',
 '.7',
 '.0',
 '.4',
 '.9',
 '.0',
 '.2',
 '.0',
 '.4',
 '.8',
 '.6',
 '.2',
 '.4',
 '.4',
 '.9',
 '.4',
 '.2',
 '.1',
 '.3',
 '.8',
 '.5',
 '.9',
 '.6',
 '.9',
 '.1',
 '.7',
 '.2',
 '.2',
 '.7',
 '.0',
 '.2',
 '.1',
 '.4',
 '.8',
 '.8',
 '.1',
 '.3',
 '.6',
 '.8',
 '.1',
 '.3',
 '.2',
 '.9',
 '.5',
 '.4',
 '.5',
 '.5',
 '.2',
 '.2',
 '.9',
 '.1',
 '.3',
 '.3',
 '.0',
 '.2',
 '.2',
 '.8',
 '.4',
 '.5',
 '.6',
 '.0',
 '.9',
 '.6',
 '.5',
 '.3',
 '.7',
 '.6',
 '.6',
 '.7',
 '.3',
 '.3',
 '.3',
 '.8',
 '.1',
 '.7',
 '.5',
 '.8',
 '.2',
 '.4',
 '.2',
 '.3',
 '.6',
 '.6',
 '.7',
 '.4',
 '.5',
 '.0',
 '.1',
 '.0',
 '.8',
 '.0',
 '.0',
 '.7',
 '.2',
 '.0',
 '.2',
 '.4',
 '.2',
 '.9',
 '.8',
 '.2',
 '.2',
 '.8',
 '.3',
 '.1',
 '.5',
 '.5',
 '.3',
 '.8',
 '.4',
 '.6',
 '.3',
 '.5',
 '.7',
 '.1',
 '.1',
 '.8',
 '.5',
 '.1',
 '.3',
 '.1',
 '.0',
 '.2',
 '.7',
 '.3',
 '.2',
 '.9',
 '.3',
 '.1',
 '.3',
 '.5',
 '.7',
 '.6',
 '.2',
 '.2',
 '.8',
 '.2',
 '.0',
 '.8',
 '.6',
 '.8',
 '.2',
 '.6',
 '.3',
 '.6',
 '.1',
 '.0',
 '.4',
 '.2',
 '.0',
 '.8',
 '.3',
 '.8',
 '.1',
 '.9',
 '.3',
 '.9',
 '.0',
 '.3',
 '.3',
 '.0',
 '.0',
 '.6',
 '.4',
 '.0',
 '.5',
 '.8',
 '.1',
 '.4',
 '.8',
 '.9',
 '.3',
 '.3',
 '.7',
 '.4',
 '.6',
 '.2',
 '.5',
 '.1',
 '.4',
 '.4',
 '.7',
 '.7',
 '.2',
 '.2',
 '.7',
 '.7',
 '.7',
 '.8',
 '.1',
 '.0',
 '.9',
 '.5',
 '.5',
 '.0',
 '.9',
 '.1',
 '.1',
 '.0',
 '.1',
 '.4',
 '.5',
 '.7',
 '.1',
 '.3',
 '.8',
 '.6',
 '.1',
 '.5',
 '.1',
 '.1',
 '.4',
 '.9',
 '.7',
 '.2',
 '.0',
 '.2',
 '.6',
 '.5',
 '.1',
 '.5',
 '.6',
 '.8',
 '.4',
 '.6',
 '.2',
 '.0',
 '.3',
 '.7',
 '.6',
 '.0',
 '.1',
 '.6',
 '.7',
 '.3',
 '.2',
 '.1',
 '.3',
 '.4',
 '.8',
 '.2',
 '.0',
 '.6',
 '.6',
 '.5',
 '.5',
 '.0',
 '.2',
 '.4',
 '.7',
 '.1',
 '.4',
 '.2',
 '.5',
 '.6',
 '.7',
 '.1',
 '.1',
 '.1',
 '.9',
 '.4',
 '.4',
 '.8',
 '.5',
 '.0',
 '.3',
 '.1',
 '.5',
 '.0',
 '.4',
 '.3',
 '.4',
 '.0',
 '.0',
 '.3',
 '.6',
 '.9',
 '.3',
 '.0',
 '.8',
 '.2',
 '.4',
 '.4',
 '.4',
 '.3',
 '.4',
 '.6',
 '.0',
 '.7',
 '.3',
 '.0',
 '.2',
 '.5',
 '.1',
 '.7',
 '.2',
 '.2',
 '.2',
 '.2',
 '.0',
 '.4',
 '.4',
 '.1',
 '.7',
 '.6',
 '.3',
 '.9',
 '.4',
 '.3',
 '.1',
 '.4',
 '.4',
 '.9',
 '.7',
 '.8',
 '.6',
 '.7',
 '.3',
 '.4',
 '.4',
 '.1',
 '.2',
 '.1',
 '.1',
 '.5',
 '.6',
 '.1',
 '.6',
 '.1',
 '.0',
 '.2',
 '.7',
 '.3',
 '.9',
 '.2',
 '.9',
 '.3',
 '.0',
 '.1',
 '.0',
 '.0',
 '.5',
 '.2',
 '.0',
 '.0',
 '.1',
 '.0',
 '.1',
 '.1',
 '.6',
 '.2',
 '.7',
 '.0',
 '.0',
 '.3',
 '.2',
 '.1',
 '.0',
 '.3',
 '.3',
 '.6',
 '.3',
 '.2',
 '.2',
 '.5',
 '.2',
 '.0',
 '.5',
 '.1',
 '.9',
 '.1',
 '.5',
 '.1',
 '.0',
 '.1',
 '.2',
 '.4',
 '.6',
 '.0',
 '.9',
 '.0',
 '.2',
 '.3',
 '.3',
 '.5',
 '.6',
 '.5',
 '.7',
 '.4',
 '.3',
 '.2',
 '.9',
 '.5',
 '.0',
 '.2',
 '.4',
 '.1',
 '.8',
 '.3',
 '.3',
 '.6',
 '.1',
 '.0',
 '.0',
 '.0',
 '.0',
 '.9',
 '.8',
 '.0',
 '.3',
 '.3',
 '.2',
 '.4',
 '.1',
 '.0',
 '.7',
 '.2',
 '.6',
 '.5',
 '.6',
 '.5',
 '.5',
 '.4',
 '.0',
 '.0',
 '.5',
 '.9',
 '.9',
 '.7',
 '.8',
 '.4',
 '.2',
 '.9',
 '.8',
 '.9',
 '.1',
 '.5',
 '.6',
 '.6',
 '.0',
 '.4',
 '.6',
 '.9',
 '.5',
 '.9',
 '.7',
 '.6',
 '.1',
 '.5',
 '.8',
 '.1',
 '.3',
 '.3',
 '.1',
 '.3',
 '.0',
 '.5',
 '.3',
 '.8',
 '.8',
 '.9',
 '.0',
 '.6',
 '.6',
 '.3',
 '.6',
 '.2',
 '.8',
 '.6',
 '.1',
 '.0',
 '.4',
 '.7',
 '.1',
 '.0',
 '.6',
 '.4',
 '.4',
 '.0',
 '.8',
 '.2',
 '.6',
 '.4',
 '.2',
 '.6',
 '.0',
 '.0',
 '.2',
 '.6',
 '.9',
 '.9',
 '.0',
 '.9',
 '.0',
 '.0',
 '.2',
 '.4',
 '.4',
 '.1',
 '.2',
 '.2',
 '.0',
 '.0',
 '.3',
 '.1',
 '.9',
 '.5',
 '.6',
 '.6',
 '.0',
 '.5',
 '.9',
 '.1',
 '.2',
 '.1',
 '.2',
 '.1',
 '.3',
 '.3',
 '.3',
 '.6',
 '.4',
 '.1',
 '.3',
 '.6',
 '.8',
 '.9',
 '.9',
 '.7',
 '.8',
 '.0',
 '.9',
 '.8',
 '.4',
 '.4',
 '.5',
 '.4',
 '.0',
 '.6',
 ...]

In [72]:
df['WindReading'] = WindReadings

In [73]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,Athlete,WindReading
0,1,9.58,+0.9,Usain,Bolt,JAM,21.08.86,1,Berlin,16.08.2009,None,None,None,None,None,None,UsainBolt,.9
1,2,9.63,+1.5,Usain,Bolt,JAM,21.08.86,1,London,05.08.2012,None,None,None,None,None,None,UsainBolt,.5
2,3,9.69,±0.0,Usain,Bolt,JAM,21.08.86,1,Beijing,16.08.2008,None,None,None,None,None,None,UsainBolt,.0
3,3,9.69,+2.0,Tyson,Gay,USA,09.08.82,1,Shanghai,20.09.2009,None,None,None,None,None,None,TysonGay,.0
4,3,9.69,-0.1,Yohan,Blake,JAM,26.12.89,1,Lausanne,23.08.2012,None,None,None,None,None,None,YohanBlake,.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4096,3678,10.09,+0.9,Reece,Prescod,GBR,29.02.96,1s1,Manchester,08.07.2023,None,None,None,None,None,None,ReecePrescod,.9
4097,3678,10.09,+2.0,Tyler,Azcano,USA,08.03.04,2,Eugene,08.07.2023,None,None,None,None,None,None,TylerAzcano,.0
4098,3678,10.09,-0.1,Ackeem,Blake,JAM,21.01.02,2,Székesfehérvár,18.07.2023,None,None,None,None,None,None,AckeemBlake,.1
4099,3678,10.09,+0.3,Abdul,Hakim,Sani,Brown,JPN,06.03.99,1rB,Luzern,20.07.2023,None,None,None,None,AbdulHakim,.3
4100,3678,10.09,+0.5,Arthur,Gue,Cissé,CIV,29.12.96,4rA,Luzern,20.07.2023,None,None,None,None,None,ArthurGue,.5

In [74]:
WorkingDataSet = df[[0, 1,'WindReading','Athlete',5,6,8,9]]
WorkingDataSet

,0,1,WindReading,Athlete,5,6,8,9
0,1,9.58,.9,UsainBolt,JAM,21.08.86,Berlin,16.08.2009
1,2,9.63,.5,UsainBolt,JAM,21.08.86,London,05.08.2012
2,3,9.69,.0,UsainBolt,JAM,21.08.86,Beijing,16.08.2008
3,3,9.69,.0,TysonGay,USA,09.08.82,Shanghai,20.09.2009
4,3,9.69,.1,YohanBlake,JAM,26.12.89,Lausanne,23.08.2012
...,...,...,...,...,...,...,...,...
4096,3678,10.09,.9,ReecePrescod,GBR,29.02.96,Manchester,08.07.2023
4097,3678,10.09,.0,TylerAzcano,USA,08.03.04,Eugene,08.07.2023
4098,3678,10.09,.1,AckeemBlake,JAM,21.01.02,Székesfehérvár,18.07.2023
4099,3678,10.09,.3,AbdulHakim,Sani,Brown,06.03.99,1rB
4100,3678,10.09,.5,ArthurGue,Cissé,CIV,4rA,Luzern

In [75]:
new_column_names = ['RANKINGS','TIMES','WINDREADING','ATHLETE','COUNTRY','BIRTHYEAR','LOCATION',"DATEOFRUN"]
WorkingDataSet.columns = new_column_names
WorkingDataSet

,RANKINGS,TIMES,WINDREADING,ATHLETE,COUNTRY,BIRTHYEAR,LOCATION,DATEOFRUN
0,1,9.58,.9,UsainBolt,JAM,21.08.86,Berlin,16.08.2009
1,2,9.63,.5,UsainBolt,JAM,21.08.86,London,05.08.2012
2,3,9.69,.0,UsainBolt,JAM,21.08.86,Beijing,16.08.2008
3,3,9.69,.0,TysonGay,USA,09.08.82,Shanghai,20.09.2009
4,3,9.69,.1,YohanBlake,JAM,26.12.89,Lausanne,23.08.2012
...,...,...,...,...,...,...,...,...
4096,3678,10.09,.9,ReecePrescod,GBR,29.02.96,Manchester,08.07.2023
4097,3678,10.09,.0,TylerAzcano,USA,08.03.04,Eugene,08.07.2023
4098,3678,10.09,.1,AckeemBlake,JAM,21.01.02,Székesfehérvár,18.07.2023
4099,3678,10.09,.3,AbdulHakim,Sani,Brown,06.03.99,1rB
4100,3678,10.09,.5,ArthurGue,Cissé,CIV,4rA,Luzern

In [76]:
WorkingDataSet.to_csv('ProMens100m.csv', index=False)