In [1]:
import math
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd
import requests
import numpy as np
import lxml
import re
from random import seed
from collections import Counter
from sklearn.linear_model import LinearRegression
from datetime import datetime
import matplotlib.pyplot as plt
import array
from sklearn.model_selection import train_test_split

C:\Users\MoJo\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.25.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

# Get Link into DataFrame

In [6]:
# URL of the webpage
url = "http://www.alltime-athletics.com/m_110hok.htm"

# Send an HTTP GET request to the URL
response = requests.get(url)

# Parse the HTML content using Beautiful Soup
soup = BeautifulSoup(response.content, "html.parser")

# Use select to find all <pre> elements
pre_elements = soup.select("pre")

In [8]:
# Select the second <pre> element
if len(pre_elements) > 1:
    first_pre_element = pre_elements[0]

    # Get the text content of the second <pre> element
    first_pre_text = first_pre_element.get_text()

    # Split the text into rows
    rows = first_pre_text.strip().split('\n')

    # Split rows into columns
    data = [row.split() for row in rows]

    # Create a Pandas DataFrame
    df = pd.DataFrame(data)
    
    print(df)
else:
    print("No second <pre> element found.")

        0      1     2        3           4         5         6         7   \
0        1  12.80  +0.3    Aries     Merritt       USA  24.07.85         1
1        2  12.81  +1.8    Grant    Holloway       USA  19.11.97       1s1
2        3  12.84  +1.6    Devon       Allen       USA  12.12.94         1
3        4  12.87  +0.9   Dayron      Robles       CUB  19.11.86       1rA
4        5  12.88  +1.1      Liu       Xiang       CHN  13.07.83       1rA
...    ...    ...   ...      ...         ...       ...       ...       ...
8829  8408  13.50  -0.6    Roger   Valentine  Iribarne       CUB  02.01.96
8830  8408  13.50  -0.1       Xu      Zhuoyi       CHN  21.08.03         2
8831  8408  13.50  -0.2   Rafael    Henrique   Pereira       BRA  08.04.97
8832  8408  13.50  +0.5  Freddie  Crittenden       USA  03.08.94        6=
8833  8408  13.50  +0.5  Michael     Dickson       USA  25.01.97        6=

                  8           9           10          11    12    13    14
0          Bruxelles  07.09.2012        None        None  None  None  None
1             Eugene  26.06.2021        None        None  None  None  None
2                New        York        City  12.06.2022  None  None  None
3            Ostrava  12.06.2008        None        None  None  None  None
4           Lausanne  11.07.2006        None        None  None  None  None
...              ...         ...         ...         ...   ...   ...   ...
8829               3   Tomblaine  18.06.2023        None  None  None  None
8830        Shenyang  29.06.2023        None        None  None  None  None
8831             5h2     Chorzów  16.07.2023        None  None  None  None
8832  Székesfehérvár  18.07.2023        None        None  None  None  None
8833  Székesfehérvár  18.07.2023        None        None  None  None  None

[8834 rows x 15 columns]

In [9]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,1,12.80,+0.3,Aries,Merritt,USA,24.07.85,1,Bruxelles,07.09.2012,None,None,None,None,None
1,2,12.81,+1.8,Grant,Holloway,USA,19.11.97,1s1,Eugene,26.06.2021,None,None,None,None,None
2,3,12.84,+1.6,Devon,Allen,USA,12.12.94,1,New,York,City,12.06.2022,None,None,None
3,4,12.87,+0.9,Dayron,Robles,CUB,19.11.86,1rA,Ostrava,12.06.2008,None,None,None,None,None
4,5,12.88,+1.1,Liu,Xiang,CHN,13.07.83,1rA,Lausanne,11.07.2006,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8829,8408,13.50,-0.6,Roger,Valentine,Iribarne,CUB,02.01.96,3,Tomblaine,18.06.2023,None,None,None,None
8830,8408,13.50,-0.1,Xu,Zhuoyi,CHN,21.08.03,2,Shenyang,29.06.2023,None,None,None,None,None
8831,8408,13.50,-0.2,Rafael,Henrique,Pereira,BRA,08.04.97,5h2,Chorzów,16.07.2023,None,None,None,None
8832,8408,13.50,+0.5,Freddie,Crittenden,USA,03.08.94,6=,Székesfehérvár,18.07.2023,None,None,None,None,None
8833,8408,13.50,+0.5,Michael,Dickson,USA,25.01.97,6=,Székesfehérvár,18.07.2023,None,None,None,None,None

In [10]:
df["Athlete"] = df[3].astype(str)+df[4].astype(str)

In [11]:
WindReadings = []
for i in range(0,len(df)):
    WindReadings.append(df[2][i][2:])
WindReadings

['.3',
 '.8',
 '.6',
 '.9',
 '.1',
 '.5',
 '.5',
 '.1',
 '.6',
 '.7',
 '.5',
 '.3',
 '.2',
 '.1',
 '.9',
 '.2',
 '.5',
 '.0',
 '.3',
 '.6',
 '.2',
 '.0',
 '.6',
 '.1',
 '.7',
 '.3',
 '.2',
 '.6',
 '.0',
 '.6',
 '.8',
 '.1',
 '.8',
 '.5',
 '.7',
 '.6',
 '.5',
 '.7',
 '.0',
 '.7',
 '.9',
 '.2',
 '.6',
 '.4',
 '.6',
 '.3',
 '.4',
 '.3',
 '.0',
 '.6',
 '.5',
 '.5',
 '.0',
 '.0',
 '.3',
 '.4',
 '.2',
 '.0',
 '.1',
 '.5',
 '.2',
 '.2',
 '.3',
 '.6',
 '.3',
 '.5',
 '.2',
 '.9',
 '.5',
 '.1',
 '.2',
 '.8',
 '.5',
 '.2',
 '.3',
 '.2',
 '.7',
 '.4',
 '.2',
 '.5',
 '.7',
 '.6',
 '.0',
 '.9',
 '.5',
 '.1',
 '.3',
 '.6',
 '.1',
 '.6',
 '.8',
 '.2',
 '.3',
 '.8',
 '.0',
 '.3',
 '.3',
 '.8',
 '.2',
 '.6',
 '.0',
 '.4',
 '.3',
 '.0',
 '.8',
 '.1',
 '.2',
 '.2',
 '.4',
 '.9',
 '.3',
 '.1',
 '.6',
 '.0',
 '.6',
 '.3',
 '.6',
 '.9',
 '.5',
 '.9',
 '.5',
 '.2',
 '.3',
 '.1',
 '.5',
 '.7',
 '.4',
 '.1',
 '.0',
 '.2',
 '.3',
 '.3',
 '.3',
 '.0',
 '.1',
 '.8',
 '.2',
 '.4',
 '.0',
 '.9',
 '.5',
 '.1',
 '.0',
 '.9',
 '.4',
 '.2',
 '.2',
 '.6',
 '.1',
 '.4',
 '.0',
 '.6',
 '.5',
 '.0',
 '.1',
 '.6',
 '.3',
 '.0',
 '.3',
 '.0',
 '.7',
 '.3',
 '.1',
 '.1',
 '.2',
 '.0',
 '.4',
 '.6',
 '.2',
 '.3',
 '.4',
 '.1',
 '.0',
 '.8',
 '.0',
 '.3',
 '.5',
 '.2',
 '.9',
 '.6',
 '.5',
 '.4',
 '.8',
 '.8',
 '.6',
 '.9',
 '.0',
 '.6',
 '.8',
 '.1',
 '.1',
 '.1',
 '.2',
 '.3',
 '.9',
 '.6',
 '.8',
 '.4',
 '.2',
 '.1',
 '.7',
 '.0',
 '.6',
 '.5',
 '.4',
 '.7',
 '.7',
 '.6',
 '.5',
 '.5',
 '.0',
 '.9',
 '.2',
 '.6',
 '.0',
 '.2',
 '.8',
 '.0',
 '.0',
 '.3',
 '.6',
 '.4',
 '.9',
 '.4',
 '.6',
 '.4',
 '.5',
 '.5',
 '.5',
 '.7',
 '.9',
 '.2',
 '.6',
 '.6',
 '.6',
 '.0',
 '.2',
 '.3',
 '.0',
 '.3',
 '.4',
 '.3',
 '.2',
 '.9',
 '.6',
 '.0',
 '.4',
 '.0',
 '.6',
 '.6',
 '.8',
 '.0',
 '.6',
 '.3',
 '.2',
 '.7',
 '.2',
 '.1',
 '.0',
 '.0',
 '.2',
 '.7',
 '.0',
 '.7',
 '.3',
 '.4',
 '.8',
 '.2',
 '.8',
 '.0',
 '.8',
 '.3',
 '.5',
 '.3',
 '.6',
 '.8',
 '.6',
 '.2',
 '.5',
 '.5',
 '.5',
 '.4',
 '.6',
 '.2',
 '.1',
 '.6',
 '.8',
 '.7',
 '.2',
 '.2',
 '.2',
 '.7',
 '.8',
 '.6',
 '.7',
 '.1',
 '.0',
 '.4',
 '.2',
 '.2',
 '.6',
 '.6',
 '.1',
 '.5',
 '.0',
 '.6',
 '.0',
 '.4',
 '.2',
 '.0',
 '.6',
 '.1',
 '.2',
 '.6',
 '.9',
 '.4',
 '.1',
 '.3',
 '.1',
 '.0',
 '.7',
 '.2',
 '.1',
 '.2',
 '.3',
 '.8',
 '.9',
 '.7',
 '.3',
 '.1',
 '.2',
 '.2',
 '.9',
 '.6',
 '.3',
 '.3',
 '.2',
 '.5',
 '.0',
 '.6',
 '.0',
 '.9',
 '.6',
 '.8',
 '.1',
 '.4',
 '.1',
 '.1',
 '.0',
 '.0',
 '.4',
 '.1',
 '.3',
 '.3',
 '.2',
 '.0',
 '.1',
 '.0',
 '.0',
 '.0',
 '.0',
 '.2',
 '.0',
 '.5',
 '.6',
 '.0',
 '.0',
 '.7',
 '.5',
 '.2',
 '.1',
 '.2',
 '.2',
 '.0',
 '.5',
 '.2',
 '.8',
 '.0',
 '.1',
 '.5',
 '.9',
 '.2',
 '.6',
 '.5',
 '.2',
 '.1',
 '.9',
 '.3',
 '.0',
 '.4',
 '.2',
 '.3',
 '.2',
 '.4',
 '.4',
 '.4',
 '.1',
 '.4',
 '.1',
 '.6',
 '.1',
 '.9',
 '.8',
 '.3',
 '.5',
 '.4',
 '.9',
 '.0',
 '.2',
 '.1',
 '.3',
 '.1',
 '.6',
 '.4',
 '.1',
 '.2',
 '.4',
 '.6',
 '.5',
 '.1',
 '.7',
 '.0',
 '.2',
 '.2',
 '.1',
 '.3',
 '.4',
 '.0',
 '.0',
 '.7',
 '.0',
 '.2',
 '.4',
 '.6',
 '.4',
 '.1',
 '.5',
 '.2',
 '.0',
 '.5',
 '.5',
 '.3',
 '.1',
 '.3',
 '.0',
 '.3',
 '.5',
 '.8',
 '.5',
 '.4',
 '.4',
 '.5',
 '.2',
 '.2',
 '.1',
 '.8',
 '.0',
 '.6',
 '.4',
 '.6',
 '.8',
 '.3',
 '.2',
 '.1',
 '.5',
 '.6',
 '.4',
 '.5',
 '.5',
 '.5',
 '.9',
 '.8',
 '.3',
 '.0',
 '.8',
 '.4',
 '.7',
 '.4',
 '.6',
 '.1',
 '.7',
 '.0',
 '.6',
 '.0',
 '.1',
 '.5',
 '.2',
 '.5',
 '.8',
 '.8',
 '.0',
 '.8',
 '.8',
 '.0',
 '.2',
 '.2',
 '.7',
 '.5',
 '.6',
 '.0',
 '.3',
 '.0',
 '.3',
 '.0',
 '.8',
 '.2',
 '.6',
 '.3',
 '.9',
 '.5',
 '.1',
 '.0',
 '.2',
 '.1',
 '.7',
 '.9',
 '.5',
 '.0',
 '.4',
 '.1',
 '.7',
 '.7',
 '.0',
 '.3',
 '.5',
 '.1',
 '.0',
 '.4',
 '.0',
 '.3',
 '.3',
 '.0',
 '.5',
 '.6',
 '.1',
 '.5',
 '.0',
 '.4',
 '.2',
 '.4',
 '.0',
 '.5',
 '.2',
 '.7',
 '.9',
 '.0',
 '.7',
 '.3',
 '.9',
 '.7',
 '.7',
 '.1',
 '.0',
 '.0',
 '.1',
 '.3',
 '.4',
 '.4',
 '.0',
 '.2',
 '.7',
 '.5',
 '.4',
 '.7',
 '.5',
 '.4',
 '.0',
 '.0',
 '.4',
 '.0',
 '.4',
 '.7',
 '.6',
 '.7',
 '.1',
 '.2',
 '.7',
 '.6',
 '.3',
 '.6',
 '.6',
 '.3',
 '.5',
 '.4',
 '.0',
 '.0',
 '.1',
 '.8',
 '.2',
 '.1',
 '.2',
 '.4',
 '.5',
 '.5',
 '.0',
 '.0',
 '.4',
 '.4',
 '.6',
 '.3',
 '.5',
 '.0',
 '.3',
 '.8',
 '.4',
 '.1',
 '.4',
 '.3',
 '.4',
 '.9',
 '.3',
 '.7',
 '.1',
 '.2',
 '.5',
 '.1',
 '.9',
 '.6',
 '.0',
 '.0',
 '.6',
 '.0',
 '.6',
 '.2',
 '.3',
 '.1',
 '.5',
 '.8',
 '.6',
 '.2',
 '.1',
 '.0',
 '.3',
 '.3',
 '.3',
 '.2',
 '.7',
 '.0',
 '.0',
 '.1',
 '.3',
 '.0',
 '.1',
 '.7',
 '.0',
 '.0',
 '.2',
 '.3',
 '.6',
 '.5',
 '.4',
 '.9',
 '.2',
 '.3',
 '.8',
 '.5',
 '.4',
 '.2',
 '.1',
 '.9',
 '.0',
 '.3',
 '.2',
 '.9',
 '.0',
 '.1',
 '.6',
 '.3',
 '.0',
 '.0',
 '.3',
 '.0',
 '.2',
 '.2',
 '.5',
 '.5',
 '.2',
 '.4',
 '.1',
 '.0',
 '.5',
 '.8',
 '.8',
 '.5',
 '.3',
 '.0',
 '.1',
 '.2',
 '.4',
 '.2',
 '.2',
 '.0',
 '.5',
 '.5',
 '.5',
 '.5',
 '.7',
 '.1',
 '.3',
 '.0',
 '.6',
 '.6',
 '.0',
 '.1',
 '.1',
 '.4',
 '.1',
 '.5',
 '.5',
 '.3',
 '.5',
 '.2',
 '.3',
 '.1',
 '.5',
 '.5',
 '.1',
 '.0',
 '.0',
 '.7',
 '.1',
 '.8',
 '.3',
 '.3',
 '.2',
 '.4',
 '.2',
 '.5',
 '.5',
 '.5',
 '.7',
 '.2',
 '.0',
 '.0',
 '.7',
 '.1',
 '.1',
 '.2',
 '.2',
 '.1',
 '.0',
 '.4',
 '.3',
 '.1',
 '.6',
 '.0',
 '.6',
 '.1',
 '.0',
 '.1',
 '.5',
 '.0',
 '.1',
 '.3',
 '.9',
 '.9',
 '.5',
 '.6',
 '.3',
 '.1',
 '.3',
 '.6',
 '.3',
 '.8',
 '.1',
 '.0',
 '.2',
 '.0',
 '.5',
 '.6',
 '.4',
 '.7',
 '.0',
 '.1',
 '.5',
 '.2',
 '.0',
 '.5',
 '.5',
 '.1',
 '.3',
 '.5',
 '.0',
 '.9',
 '.2',
 '.4',
 '.6',
 '.4',
 '.7',
 '.1',
 '.3',
 '.5',
 '.0',
 '.0',
 '.0',
 '.0',
 '.3',
 '.7',
 '.1',
 '.2',
 '.3',
 '.6',
 '.2',
 '.4',
 '.0',
 '.0',
 '.9',
 '.1',
 '.4',
 '.7',
 '.5',
 '.3',
 '.6',
 '.3',
 '.4',
 '.4',
 '.6',
 '.0',
 '.1',
 '.0',
 '.4',
 '.1',
 '.9',
 '.2',
 '.5',
 '.8',
 '.8',
 '.6',
 '.7',
 '.9',
 '.6',
 '.6',
 '.5',
 '.9',
 '.2',
 '.3',
 '.8',
 '.4',
 '.0',
 '.6',
 '.0',
 '.7',
 '.0',
 '.0',
 '.6',
 '.4',
 '.6',
 '.0',
 '.6',
 '.5',
 '.8',
 '.8',
 '.3',
 '.5',
 '.6',
 '.5',
 '.2',
 '.0',
 '.6',
 '.9',
 '.0',
 '.5',
 '.4',
 '.0',
 '.0',
 '.7',
 '.1',
 '.6',
 '.6',
 '.7',
 '.6',
 '.2',
 '.7',
 '.1',
 '.1',
 '.0',
 '.5',
 '.6',
 '.1',
 '.0',
 '.0',
 '.4',
 '.4',
 '.2',
 '.5',
 '.9',
 '.2',
 '.1',
 '.5',
 '.5',
 '.7',
 '.5',
 '.1',
 '.4',
 '.8',
 '.5',
 '.2',
 '.7',
 '.0',
 '.3',
 '.5',
 '.2',
 '.3',
 '.3',
 '.3',
 '.4',
 '.0',
 '.7',
 '.8',
 '.1',
 '.2',
 '.1',
 '.1',
 '.9',
 '.0',
 '.2',
 '.3',
 '.7',
 '.2',
 '.3',
 '.5',
 '.2',
 '.0',
 '.0',
 '.7',
 '.8',
 '.2',
 '.1',
 '.8',
 '.0',
 '.6',
 '.2',
 '.2',
 '.6',
 '.4',
 '.5',
 '.4',
 '.2',
 '.2',
 '.0',
 '.4',
 '.2',
 '.0',
 '.6',
 '.7',
 '.5',
 '.2',
 '.5',
 '.2',
 '.3',
 '.0',
 '.4',
 '.0',
 '.6',
 '.4',
 '.1',
 '.3',
 '.3',
 '.3',
 '.0',
 '.3',
 '.2',
 '.2',
 '.7',
 '.0',
 '.1',
 '.1',
 '.0',
 '.1',
 '.5',
 '.1',
 '.3',
 '.1',
 '.8',
 '.5',
 '.0',
 '.0',
 '.0',
 '.1',
 '.7',
 '.3',
 '.5',
 '.6',
 '.2',
 '.7',
 '.8',
 '.3',
 '.0',
 '.3',
 '.9',
 '.3',
 '.6',
 '.1',
 '.9',
 '.8',
 '.3',
 '.8',
 '.3',
 '.8',
 '.8',
 ...]

In [12]:
df['WindReading'] = WindReadings

In [13]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,Athlete,WindReading
0,1,12.80,+0.3,Aries,Merritt,USA,24.07.85,1,Bruxelles,07.09.2012,None,None,None,None,None,AriesMerritt,.3
1,2,12.81,+1.8,Grant,Holloway,USA,19.11.97,1s1,Eugene,26.06.2021,None,None,None,None,None,GrantHolloway,.8
2,3,12.84,+1.6,Devon,Allen,USA,12.12.94,1,New,York,City,12.06.2022,None,None,None,DevonAllen,.6
3,4,12.87,+0.9,Dayron,Robles,CUB,19.11.86,1rA,Ostrava,12.06.2008,None,None,None,None,None,DayronRobles,.9
4,5,12.88,+1.1,Liu,Xiang,CHN,13.07.83,1rA,Lausanne,11.07.2006,None,None,None,None,None,LiuXiang,.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8829,8408,13.50,-0.6,Roger,Valentine,Iribarne,CUB,02.01.96,3,Tomblaine,18.06.2023,None,None,None,None,RogerValentine,.6
8830,8408,13.50,-0.1,Xu,Zhuoyi,CHN,21.08.03,2,Shenyang,29.06.2023,None,None,None,None,None,XuZhuoyi,.1
8831,8408,13.50,-0.2,Rafael,Henrique,Pereira,BRA,08.04.97,5h2,Chorzów,16.07.2023,None,None,None,None,RafaelHenrique,.2
8832,8408,13.50,+0.5,Freddie,Crittenden,USA,03.08.94,6=,Székesfehérvár,18.07.2023,None,None,None,None,None,FreddieCrittenden,.5
8833,8408,13.50,+0.5,Michael,Dickson,USA,25.01.97,6=,Székesfehérvár,18.07.2023,None,None,None,None,None,MichaelDickson,.5

In [14]:
WorkingDataSet = df[[0, 1, 'Athlete','WindReading',5,6,8,9]]
WorkingDataSet

,0,1,Athlete,WindReading,5,6,8,9
0,1,12.80,AriesMerritt,.3,USA,24.07.85,Bruxelles,07.09.2012
1,2,12.81,GrantHolloway,.8,USA,19.11.97,Eugene,26.06.2021
2,3,12.84,DevonAllen,.6,USA,12.12.94,New,York
3,4,12.87,DayronRobles,.9,CUB,19.11.86,Ostrava,12.06.2008
4,5,12.88,LiuXiang,.1,CHN,13.07.83,Lausanne,11.07.2006
...,...,...,...,...,...,...,...,...
8829,8408,13.50,RogerValentine,.6,Iribarne,CUB,3,Tomblaine
8830,8408,13.50,XuZhuoyi,.1,CHN,21.08.03,Shenyang,29.06.2023
8831,8408,13.50,RafaelHenrique,.2,Pereira,BRA,5h2,Chorzów
8832,8408,13.50,FreddieCrittenden,.5,USA,03.08.94,Székesfehérvár,18.07.2023
8833,8408,13.50,MichaelDickson,.5,USA,25.01.97,Székesfehérvár,18.07.2023

In [15]:
new_column_names = ['RANKINGS','TIMES','ATHLETE','WINDREADING','COUNTRY','BIRTHYEAR','LOCATION','DATEOFRUN']
WorkingDataSet.columns = new_column_names
WorkingDataSet

,RANKINGS,TIMES,ATHLETE,WINDREADING,COUNTRY,BIRTHYEAR,LOCATION,DATEOFRUN
0,1,12.80,AriesMerritt,.3,USA,24.07.85,Bruxelles,07.09.2012
1,2,12.81,GrantHolloway,.8,USA,19.11.97,Eugene,26.06.2021
2,3,12.84,DevonAllen,.6,USA,12.12.94,New,York
3,4,12.87,DayronRobles,.9,CUB,19.11.86,Ostrava,12.06.2008
4,5,12.88,LiuXiang,.1,CHN,13.07.83,Lausanne,11.07.2006
...,...,...,...,...,...,...,...,...
8829,8408,13.50,RogerValentine,.6,Iribarne,CUB,3,Tomblaine
8830,8408,13.50,XuZhuoyi,.1,CHN,21.08.03,Shenyang,29.06.2023
8831,8408,13.50,RafaelHenrique,.2,Pereira,BRA,5h2,Chorzów
8832,8408,13.50,FreddieCrittenden,.5,USA,03.08.94,Székesfehérvár,18.07.2023
8833,8408,13.50,MichaelDickson,.5,USA,25.01.97,Székesfehérvár,18.07.2023

In [16]:
WorkingDataSet.to_csv('Mens110mHurdles.csv', index=False)