### Import Packages

In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options
from selenium.webdriver .chrome.service import Service
import time
import pandas as pd

In [2]:
from selenium.webdriver.support import expected_conditions as EC

### Start Selenium Driver

In [3]:

#--------------------------------------------#
service = Service()
options = webdriver.ChromeOptions()
options.add_argument('--headless')
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

### Link to Website for scraping

In [4]:
link = "http://organizeyourmusic.playlistmachinery.com/#"

In [5]:
driver.get(link)

In [6]:
MusicButton = driver.find_element(By.ID,"go")
MusicButton.click()

In [7]:
contentusername = driver.find_element(By.ID,"login-username")
contentusername.send_keys("jamoffatt.411@gmail.com")
time.sleep(5)

In [8]:
contentpassword = driver.find_element(By.ID,"login-password")
contentpassword.send_keys("Moff070500$_")
time.sleep(5)

In [9]:
contentbutton = driver.find_element(By.ID,"login-button")
contentbutton.click()

In [10]:
time.sleep(90)

In [11]:
driver.title

'Organize Your Music'

In [94]:
# Find the table element
table = driver.find_element(By.XPATH,'/html/body/div[3]/div[2]/div/div[2]/div/div/div[1]/table/div/div/table')

In [95]:
# Read the table into a DataFrame
df = pd.read_html(table.get_attribute('outerHTML'))[0]

### ResultingDataFrame

In [96]:
df

,Unnamed: 0,sel,Unnamed: 2,title,artist,top genre,year,added,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,NaN,NaN,Snooze,SZA,pop,2022,2023‑08‑05,143,55,56,-7,11,39,202,14,13,94
1,2,NaN,NaN,fukumean,Gunna,atl hip hop,2023,2023‑07‑03,130,62,85,-7,28,22,125,12,9,92
2,3,NaN,NaN,See You Again (feat. Kali Uchis),"Tyler, The Creator",hip hop,2017,2020‑09‑25,79,56,56,-9,11,62,180,37,10,92
3,4,NaN,NaN,Heartless,Kanye West,chicago rap,2008,2021‑05‑16,88,65,79,-6,25,65,211,5,14,91
4,5,NaN,NaN,Father Stretch My Hands Pt. 1,Kanye West,chicago rap,2016,2020‑09‑25,113,57,72,-4,54,44,136,12,5,91
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1761,1762,NaN,NaN,a&t,21 Savage,atl hip hop,2018,2020‑09‑25,147,57,91,-5,7,73,212,1,10,0
1762,1763,NaN,NaN,Baby Jesus - Remix,DaBaby,hip hop,2016,2020‑09‑25,120,87,82,-2,9,43,232,3,11,0
1763,1764,NaN,NaN,Clarity,Cream Dinero,atl hip hop,2019,2020‑09‑25,120,52,83,-12,35,59,241,28,18,0
1764,1765,NaN,NaN,good day,21 Savage,atl hip hop,2018,2020‑09‑25,122,51,96,-6,26,13,242,0,34,0
1765,1766,NaN,NaN,Over With,Rich The Kid,atl hip hop,2020,2020‑09‑25,145,54,84,-6,13,52,123,6,23,0

In [97]:
WorkingDataFrame = df

In [98]:
WorkingDataFrame

,Unnamed: 0,sel,Unnamed: 2,title,artist,top genre,year,added,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,NaN,NaN,Snooze,SZA,pop,2022,2023‑08‑05,143,55,56,-7,11,39,202,14,13,94
1,2,NaN,NaN,fukumean,Gunna,atl hip hop,2023,2023‑07‑03,130,62,85,-7,28,22,125,12,9,92
2,3,NaN,NaN,See You Again (feat. Kali Uchis),"Tyler, The Creator",hip hop,2017,2020‑09‑25,79,56,56,-9,11,62,180,37,10,92
3,4,NaN,NaN,Heartless,Kanye West,chicago rap,2008,2021‑05‑16,88,65,79,-6,25,65,211,5,14,91
4,5,NaN,NaN,Father Stretch My Hands Pt. 1,Kanye West,chicago rap,2016,2020‑09‑25,113,57,72,-4,54,44,136,12,5,91
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1761,1762,NaN,NaN,a&t,21 Savage,atl hip hop,2018,2020‑09‑25,147,57,91,-5,7,73,212,1,10,0
1762,1763,NaN,NaN,Baby Jesus - Remix,DaBaby,hip hop,2016,2020‑09‑25,120,87,82,-2,9,43,232,3,11,0
1763,1764,NaN,NaN,Clarity,Cream Dinero,atl hip hop,2019,2020‑09‑25,120,52,83,-12,35,59,241,28,18,0
1764,1765,NaN,NaN,good day,21 Savage,atl hip hop,2018,2020‑09‑25,122,51,96,-6,26,13,242,0,34,0
1765,1766,NaN,NaN,Over With,Rich The Kid,atl hip hop,2020,2020‑09‑25,145,54,84,-6,13,52,123,6,23,0

In [99]:
WorkingDataFrame = WorkingDataFrame.rename(columns={'Unnamed: 0': 'Number'})

In [102]:
WorkingDataFrame = WorkingDataFrame.rename(columns={'Unnamed: 2':'Number 2'})

In [103]:
WorkingDataFrame = WorkingDataFrame.drop(['sel','Number 2'],axis = 1)

### Finalized Dataframe

In [104]:
WorkingDataFrame

,Number,title,artist,top genre,year,added,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,Snooze,SZA,pop,2022,2023‑08‑05,143,55,56,-7,11,39,202,14,13,94
1,2,fukumean,Gunna,atl hip hop,2023,2023‑07‑03,130,62,85,-7,28,22,125,12,9,92
2,3,See You Again (feat. Kali Uchis),"Tyler, The Creator",hip hop,2017,2020‑09‑25,79,56,56,-9,11,62,180,37,10,92
3,4,Heartless,Kanye West,chicago rap,2008,2021‑05‑16,88,65,79,-6,25,65,211,5,14,91
4,5,Father Stretch My Hands Pt. 1,Kanye West,chicago rap,2016,2020‑09‑25,113,57,72,-4,54,44,136,12,5,91
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1761,1762,a&t,21 Savage,atl hip hop,2018,2020‑09‑25,147,57,91,-5,7,73,212,1,10,0
1762,1763,Baby Jesus - Remix,DaBaby,hip hop,2016,2020‑09‑25,120,87,82,-2,9,43,232,3,11,0
1763,1764,Clarity,Cream Dinero,atl hip hop,2019,2020‑09‑25,120,52,83,-12,35,59,241,28,18,0
1764,1765,good day,21 Savage,atl hip hop,2018,2020‑09‑25,122,51,96,-6,26,13,242,0,34,0
1765,1766,Over With,Rich The Kid,atl hip hop,2020,2020‑09‑25,145,54,84,-6,13,52,123,6,23,0

### Export to Pickle File

In [105]:
WorkingDataFrame.to_pickle('ScrapedDataframe.pkl')
print("DONE")

DONE